### ISSUE TITLE
Betterdontfail issue

### ISSUE THREAD

**Issue by avioane** [dabo123148/WarlightMod#12]
https://www.warzone.com/MultiPlayer?GameID=15012850
This game has commanders, nuke card(recon version), deployment limit @ 11, betterdontfail, and stack limit  @ 21.

I have 6 armies in Chad, he has 5 armies in Sudan.
He attacks with 5 armies into my 6. I lose 3, he loses 4.
Immediately after this attack, I have 3, he has 1.

The "Attackfailed" order sets my armies to 13. Why 13? The mod Betterdontfail says that the attacked territory loses nothing and gets the lost armies. If that's the case, my armies should be 6(my initial armies)+4(what he lost)=10. But why do I get 13?

**Comment by dabo123148** [comment]
Sorry for the late reply, I was a bit busy in RL. But I think the issue should be fixed now.
