### ISSUE TITLE
Our game crashes and will not move to next turn

### ISSUE THREAD

**Issue by LeCountH** [dabo123148/WarlightMod#13]
We have been stuck for 9 days and it won't let us boot people.
https://www.warzone.com/MultiPlayer?GameID=15179335%20p=Website&Unity=1

**Comment by dabo123148** [comment]
I am trying to take a look on the error but somehow the mod system doesn't load the error list for the mod, need to ask Fizzer for some help.

**Comment by dabo123148** [comment]
In the meantime, while i am waiting for a response, can you maybe send me the mod error.

**Comment by LeCountH** [comment]
He says ServerException: Warzone Server returned ModFailed x=ModFailed: Mod "Advanced Diplo Mod V2" Failed: [string "Server_AdvanceTurn.lua"]:323: MoonSharp.Interpreter.ScriptRuntimeException: Mod table PlayerGameData exceeded maximum size.  Found 102781 bytes, maximum is 100000
__newindex (External Function)

(Unknown Function) (Server_AdvanceTurn.lua:323)




GameID=15179335

Hook=Server_AdvanceTurn_End


Sent from Yahoo Mail for iPhone


On Thursday, April 5, 2018, 8:54 AM, dabo123148 <notifications@github.com> wrote:


In the meantime, while i am waiting for a response, can you maybe send me the mod error.

**Comment by dabo123148** [comment]
ok that could be a longer fix, which only occurs in long games with a lot of mod interaction

**Comment by dabo123148** [comment]
I think I have now a fix for it, now I only need to change some stuff so you won't get the mod history of some parts of the mod one turn later then it happens, but that shouldn't take that long. After that  I will run some tests and publish the fix

**Comment by dabo123148** [comment]
I tested it now as good as possible at the moment and published the fix, so your game should be able to continue. If you run into any problems let me know. But since I don't have a game with the error I can't guarantee 100% that it is fixed.

**Comment by dabo123148** [comment]
seems like the data i have is still too much, need to change some things then in order to reduce the data

**Comment by dabo123148** [comment]
I limited now the latest messages to a total of 10messages, maybe that helps

**Comment by LeCountH** [comment]
Error 
ServerException: Warzone Server returned ModContainerTimeout nox


Sent from Yahoo Mail for iPhone


On Friday, April 6, 2018, 6:09 AM, dabo123148 <notifications@github.com> wrote:


I limited now the latest messages to a total of 10messages, maybe that helps

**Comment by dabo123148** [comment]
I will implement in the next days(think monday since I am bussy for the next few days) a little button for you that allows you to get some debug information that help me track the usage

**Comment by dabo123148** [comment]
I also disabled now some mod messages, maybe that is already enough

**Comment by dabo123148** [comment]
also please tell me if after my changes the Warzone Server returned ModContainerTimeout nox still happens, cause that's one of the few errors I can't see when it occures

**Comment by LeCountH** [comment]
Yes it still happened

ServerException: Warzone Server returned ModContainerTimeout nox

Sent from Yahoo Mail for iPhone


On Saturday, April 7, 2018, 5:07 AM, dabo123148 <notifications@github.com> wrote:


also please tell me if after my changes the Warzone Server returned ModContainerTimeout nox still happens, cause that's one of the few errors I can't see when it occures

**Comment by dabo123148** [comment]
sorry, that I didn't worked on it yesterday, I now disabled all new messages, maybe that helps

**Comment by LeCountH** [comment]
Same message


Sent from Yahoo Mail for iPhone


On Tuesday, April 10, 2018, 1:20 PM, dabo123148 <notifications@github.com> wrote:


sorry, that I didn't worked on it yesterday, I now disabled all new messages, maybe that helps

**Comment by dabo123148** [comment]
Ok seems like it works now with my last change

**Comment by dabo123148** [comment]
although I have to undo it again(was a convertion problem of the 10message limit), so if it happens again, tell me

**Comment by LeCountH** [comment]
Thank you


Sent from Yahoo Mail for iPhone


On Wednesday, April 11, 2018, 2:23 PM, dabo123148 <notifications@github.com> wrote:


Ok seems like it works now with my last change

**Comment by LeCountH** [comment]
Ok


Sent from Yahoo Mail for iPhone


On Wednesday, April 11, 2018, 2:24 PM, dabo123148 <notifications@github.com> wrote:


although I have to undo it again(was a convertion problem of the 10message limit), so if it happens again, tell me

**Comment by LeCountH** [comment]
It won't let someone take their turn


Sent from Yahoo Mail for iPhone


On Wednesday, April 11, 2018, 2:24 PM, dabo123148 <notifications@github.com> wrote:


Closed #13.

**Comment by LeCountH** [comment]
ServerException: Warzone Server returned ModFailed x=ModFailed: Mod "Advanced Diplo Mod V2" Failed: [string "Server_AdvanceTurn.lua"]:490: MoonSharp.Interpreter.ScriptRuntimeException: Mod table PlayerGameData exceeded maximum size.  Found 100157 bytes, maximum is 100000

__newindex (External Function)

(Unknown Function) (Server_AdvanceTurn.lua:490)




GameID=15179335

Hook=Server_AdvanceTurn_End


Sent from Yahoo Mail for iPhone


On Wednesday, April 11, 2018, 2:24 PM, dabo123148 <notifications@github.com> wrote:


Closed #13.

**Comment by dabo123148** [comment]
again... now i am interested what you have in your data but i will simply change it back

**Comment by LeCountH** [comment]
I want to make peace with some of the AI why can’t I 
ServerException: Warzone Server returned ModFailed x=ModFailed: Mod "Advanced Diplo Mod V2" Failed: [string "Server_GameCustomMessage.lua"]:135: MoonSharp.Interpreter.ScriptRuntimeException: Mod table PlayerGameData exceeded maximum size.  Found 100063 bytes, maximum is 100000

__newindex (External Function)

(Unknown Function) (Server_GameCustomMessage.lua:135)




GameID=15179335

Hook=Server_GameCustomMessage


Sent from Yahoo Mail for iPhone


On Sunday, April 15, 2018, 11:50 AM, dabo123148 <notifications@github.com> wrote:


again... now i am interested what you have in your data but i will simply change it back

**Comment by dabo123148** [comment]
That is sadly something I can't really fix, it happens when the mod stores too much data(the data is required to run the mod in all functionality and so happens when the game reaches a point, where it hits the limitations of the mod framework). My workaround is, that it deletes parts of the data after each turn and so it might be possible to make peace with the ai in the next turn otherwise, you should decline/accept then all kind of offers you got since that will also reduce the data in the next turn.

**Comment by LeCountH** [comment]
Ok.


Sent from Yahoo Mail for iPhone


On Tuesday, June 12, 2018, 2:20 PM, dabo123148 <notifications@github.com> wrote:


That is sadly something I can't really fix, it happens when the mod stores too much data(the data is required to run the mod in all functionality and so happens when the game reaches a point, where it hits the limitations of the mod framework). My workaround is, that it deletes parts of the data after each turn and so it might be possible to make peace with the ai in the next turn otherwise, you should decline/accept then all kind of offers you got since that will also reduce the data in the next turn.
