### ISSUE TITLE
Alliance request

### ISSUE THREAD

**Issue by dabnug** [dabo123148/WarlightMod#15]
Hi,

I stopped the app and reloaded the maps. Now it erroring on the next line.

ServerException: Warzone Server returned ModFailed x=ModFailed: Mod "Advanced Diplo Mod V3" Failed: [string "Server_GameCustomMessage.lua"]:311: attempt to index field '?' (a nil value)
addmessagecustom (Server_GameCustomMessage.lua:311)
(Unknown Function) (Server_GameCustomMessage.lua:24)

GameID=15593128
Hook=Server_GameCustomMessage

**Comment by dabo123148** [comment]
Forgot to delete a line now it should hopefully work

On May 29, 2018 21:47, dabnug <notifications@github.com> wrote:

Hi,

I stopped the app and reloaded the maps. Now it erroring on the next line.

ServerException: Warzone Server returned ModFailed x=ModFailed: Mod "Advanced Diplo Mod V3" Failed: [string "Server_GameCustomMessage.lua"]:311: attempt to index field '?' (a nil value)
addmessagecustom (Server_GameCustomMessage.lua:311)
(Unknown Function) (Server_GameCustomMessage.lua:24)

GameID=15593128
Hook=Server_GameCustomMessage
