### ISSUE TITLE
Trade feature freezes

### ISSUE THREAD

**Issue by dabnug** [dabo123148/WarlightMod#16]
Hi,

When you select the trade feature and attempt to select a territory it freezes. No error that i can see.

Chris

**Comment by dabo123148** [comment]
That sounds pretty much like you play on a map with a lot of territories so it may happen that your device runs isn't able to work with the map. Can you maybe send me a link to the game and tell me when it freezes exactly.

On Jun 20, 2018 19:16, dabnug <notifications@github.com> wrote:

Hi,

When you select the trade feature and attempt to select a territory it freezes. No error that i can see.

Chris

**Comment by dabnug** [comment]
Same game as my other bug. I think I see why. It loads a popup of all the terr's. But there is no order. Could you perhaps sort by name?

**Comment by dabnug** [comment]
its the USA map with n1000 terrs

**Comment by dabo123148** [comment]
I assume the problem is caused either by a timeout since it takes to long to show the territories a player has or by using more resources to check which territories are owned by you then available on your device/browser so there is sadly nothing I could really do against it.

In regard to sorting the territories by name you would require even more resources and time and so it would make problems on even smaller maps.

**Comment by dabnug** [comment]
Humm, I dont think a sort would tax the system much more. Compiling the list is sorting through all 3066 territories to determine which one my user owns. Once the list is returned, then you would perform a sort? I am assuming this is using tables, is their no indexing built in?

Even without it the sort would be on a subset of total territories. Its weird that on my Pixel 2 it takes 45 seconds to load a list. I have between 300-400 terr's on the map.

**Comment by dabnug** [comment]
would it be possible to select a terr from the map? its kind of clunky to go by name. I think you can count in single digits the % of player that actually know the names of individual terr's on any map?

**Comment by dabo123148** [comment]
I just tested it, after around 1min it worked on a map with a lot of territories to interact with the menu and the data is in a array structure sorted after territory Id not name.

**Comment by dabnug** [comment]
https://forums.coronalabs.com/topic/36656-help-sort-table-alphabetically/

looks like an easy sort implementation.

I wonder which sort it uses?

**Comment by dabnug** [comment]
That looks like recursive? Its been abount 10 yrs since I sat through that class.

**Comment by dabnug** [comment]
I am currently at war and allied with the same player. The game is called turmoil started by Brian Jones. Its on the untied states big map. Min 34 is the player that I have two states on. I think he was booted once. I can see all his terr's. I do not know if I can attack him.

**Comment by dabnug** [comment]
Also, I finally worked my way through a trade. I got the notice that the offer was sent, but the recipient never got anything. A turn has rolled over and they still do not see the offer. I am at peace with this player.

**Comment by dabo123148** [comment]
I like to apologise that I haven't found yet the time to look into the issues you mentioned, but I should find tomorrow the time to fix the one in regard to multiple diplomacy states

On Jun 29, 2018 21:31, dabnug <notifications@github.com> wrote:

Also, I finally worked my way through a trade. I got the notice that the offer was sent, but the recipient never got anything. A turn has rolled over and they still do not see the offer. I am at peace with this player.

**Comment by dabo123148** [comment]
Which version of the Mod were you using, V3 or V2

**Comment by dabnug** [comment]
Vvvvvv

**Comment by dabnug** [comment]
lol. sorry my Pixel likes to freeze up sometimes. I am using v3

**Comment by dabnug** [comment]
the state feed is filled with allot of conflicting info, players at war, peace and in alliance all at the same time.

**Comment by dabnug** [comment]
I still have an outstanding trade offer that the recipient cannot see for two turns now.

**Comment by dabo123148** [comment]
you said you have an outstanding trade offer, how do you know you still have it, did you tried to send it again since if he can't see it, that normally indicates, that he has declined it or something like that, but I will take a look into it

**Comment by dabo123148** [comment]
I changed it now, that if you are allied with a player and in war with the same one, that it will be then instant cancel the alliance at the beginning of the turn-->all actions that require war are already in turn possible

**Comment by dabnug** [comment]
It says I am still in the offer at the update popup. I also asked the
player if he received it, he said no. I sent it again.

**Comment by dabnug** [comment]
Trade feature appears to be working but adding that sort would be really helpful. The window displays the name and the ID. The list is not sorted by either item. Alphabetical would be very beneficial and I dont think it would add much more time. You already have to wait 2 mins for the list to load, whats another 15-20 seconds?

**Comment by dabnug** [comment]
I bet it would sort in under 5

**Comment by dabnug** [comment]
also how do I know which trade offers are outstanding? If I am trying to give a player an entire bonus and I loose track which terrs are already "traded" how do I find the info?

**Comment by dabo123148** [comment]
There is saddly no way to see which territories you already offered except reoffering them since then you get an error when you have it already offered

Gesendet von Mail<https://go.microsoft.com/fwlink/?LinkId=550986> für Windows 10

________________________________
Von: dabnug <notifications@github.com>
Gesendet: Thursday, July 19, 2018 6:11:40 PM
An: dabo123148/WarlightMod
Cc: dabo123148; Comment
Betreff: Re: [dabo123148/WarlightMod] Trade feature freezes (#16)


also how do I know which trade offers are outstanding? If I am trying to give a player an entire bonus and I loose track which terrs are already "traded" how do I find the info?

**Comment by dabnug** [comment]
there is no way to use your mod and play a strategic game. I went through and picked out several territories on that map to give to another player and they received something totally different. Gave them about 6 terr's and it was spread across all my bonuses, only one was in the correct location. The list that shows up of terr's you own has both terr ID and name. The list is not sorted by either. I am thinking maybe there are two separate ID's and you are displaying one with the terr name and then getting them crossed at execution?

That was quite a rough game to play. I think you mod could add a fun twist to the game but you need to use it a bunch of time to work all the kinks out man!
