### ISSUE TITLE
Change percentage attack default of "LimitedMultiattack" mod

### ISSUE THREAD

**Issue by tmoerkerken** [dabo123148/WarlightMod#20]
The LimitedMultiattack mod has "Attack by percentage" checked by default. We use this mod in a way that the multi attack feature is very rare. It would make more sense to have "Attack by percentage" turned off by default in this case.

Could this be an additional configuration option for this mod? And if it already is, I'm sorry, I'm not the one that sets up the games.

![tempFileForShare_20201204-160517](https://user-images.githubusercontent.com/6529496/101179521-9d54eb00-364a-11eb-85ce-1c8369afcb61.jpg)

**Comment by dabo123148** [comment]
I don't really remember why this was done given that the mod was created 4 years ago on an early version of the mod framework, but I can check if it is still needed when I find the tine

**Comment by dabo123148** [comment]
Seems like it isn't needed anymore(or I missed it when testing), so it is now removed
